-- Create the quotations table for Air Medical India Lead Capture
CREATE TABLE quotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    full_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    email_address TEXT NOT NULL,
    service_type TEXT NOT NULL,
    status TEXT DEFAULT 'pending' -- Initial status for internal workflow
);

-- Enable Row Level Security (RLS)
ALTER TABLE quotations ENABLE ROW LEVEL SECURITY;

-- Allow anonymous form submissions (Public Insert)
CREATE POLICY "Allow public form submissions" 
ON quotations FOR INSERT 
WITH CHECK (true);

-- Allow authenticated staff to read entries
CREATE POLICY "Allow staff to read quotations" 
ON quotations FOR SELECT 
USING (auth.role() = 'authenticated');
